/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:ea1bdfc1-af28-430d-aa48-0198cf36197d",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_EV7OR8Lte",
    "aws_user_pools_web_client_id": "2pt9oievf97gnafgajfo1fgdn1",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://3hcwp2c7jba3bdzfhwzv2i4ufy.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-sjpwbhytqragngicxgo7gb7r7a"
};


export default awsmobile;
