/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "us-east-2",
  aws_cognito_identity_pool_id:
    "us-east-2:ea1bdfc1-af28-430d-aa48-0198cf36197d",
  aws_cognito_region: "us-east-2",
  aws_user_pools_id: "us-east-2_EV7OR8Lte",
  aws_user_pools_web_client_id: "2pt9oievf97gnafgajfo1fgdn1",
  oauth: {},
};

export default awsmobile;
